name: bump-macloggerdx
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  bump:
    runs-on: macos-latest
    steps:
    - uses: macauley/action-homebrew-bump-cask@v0.0.1
      with:
        # Required, custom GitHub access token with only the 'public_repo' scope enabled
        token: ${{secrets.BUMP_CASK_TOKEN}}
        # Bump all outdated casks in this tap
        tap: Homebrew/homebrew-cask
        # Bump only these casks if outdated
        cask: maxloggerdx
        livecheck: true
        dryrun: true
